# Generated by Django 3.2 on 2021-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('prn', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('profile_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
