# Generated by Django 3.2 on 2021-05-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_img',
        ),
    ]
